# Generated by Django 4.2.6 on 2023-12-13 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_order_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_Vnpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('vnp_PayDate', models.DateTimeField(auto_now_add=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_TmnCode', models.CharField(blank=True, max_length=200, null=True)),
                ('vnp_BankCode', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
