# Generated by Django 4.2.6 on 2023-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pricecsale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
