# Generated by Django 4.2.6 on 2023-11-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_pricecsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pricecsale',
            new_name='pricesale',
        ),
    ]
