# Generated by Django 4.2.6 on 2023-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_total_order_totalbook_order_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
            preserve_default=False,
        ),
    ]
