# Generated by Django 4.2.6 on 2023-11-26 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 26, 12, 38, 19, 635397, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 22, 5, 5, 24, 543070)),
            preserve_default=False,
        ),
    ]
