# Generated by Django 4.2.6 on 2023-12-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=123456788, max_length=16),
            preserve_default=False,
        ),
    ]
